### ISSUE TITLE
A couple minor issues

### ISSUE THREAD

**Issue by f2404** [zebrajr/tornfarm#2]
1. start_torn_farm_cloud.py isn't really a Python script but rather a shell script - suggest changing (or removing) the ".py" filename extension and adding a shebang.
2. https://github.com/zebrajr/tornfarm/blob/master/Torn%20Farm%20Scraper%20-%20Python/torn_farm_cloud.py#L71 says "Waiting 40 seconds" but the script actually sleeps for 50 seconds.

**Comment by zebrajr** [comment]
Not relevant anymore since Legacy mode is no longer supported.
New docker based build has the issue fixed.
